# Generated by Django 4.0.4 on 2022-05-15 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('host', models.URLField(blank=True)),
                ('shortname', models.CharField(blank=True, max_length=45)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_date', models.DateTimeField(blank=True, null=True)),
                ('archived_note', models.TextField(blank=True, null=True)),
                ('archived_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=45)),
                ('url_name', models.CharField(blank=True, max_length=45, null=True)),
                ('information', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_date', models.DateTimeField(blank=True, null=True)),
                ('archived_note', models.TextField(blank=True, null=True)),
                ('archived_by', models.CharField(blank=True, max_length=100, null=True)),
                ('application', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='data.applications')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=45)),
                ('application', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='data.applications')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('id_card_type', models.CharField(blank=True, max_length=10, null=True)),
                ('id_card_number', models.CharField(blank=True, max_length=45, null=True)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('firstname', models.CharField(blank=True, max_length=45, null=True)),
                ('lastname', models.CharField(blank=True, max_length=45, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100)),
                ('birthdate', models.DateField(default=None, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('religion', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=45, null=True)),
                ('sub_district', models.CharField(blank=True, max_length=45, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_date', models.DateTimeField(blank=True, null=True)),
                ('archived_note', models.TextField(blank=True, null=True)),
                ('archived_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('fcm_name', models.TextField(blank=True, null=True)),
                ('applications', models.ManyToManyField(blank=True, to='data.applications')),
                ('domains', models.ManyToManyField(blank=True, to='data.domains')),
                ('roles', models.ManyToManyField(blank=True, to='data.roles')),
            ],
        ),
    ]
