# Generated by Django 4.0.4 on 2022-05-29 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_domains_application_domains_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domains',
            old_name='application',
            new_name='applications',
        ),
    ]
