# Generated by Django 4.0.4 on 2022-05-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('token', models.CharField(blank=True, max_length=155)),
                ('credential', models.JSONField(blank=True)),
                ('expired_date', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_date', models.DateTimeField(blank=True, null=True)),
                ('archived_note', models.TextField(blank=True, null=True)),
                ('archived_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
